
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsCuentasSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsCuentasSoap {


    /**
     * 
     * @param reqCuentas
     * @return
     *     returns org.tempuri.ArrayOfCuentasBE
     */
    @WebMethod(operationName = "ConsultarCuentas", action = "http://tempuri.org/ConsultarCuentas")
    @WebResult(name = "ConsultarCuentasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarCuentas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCuentas")
    @ResponseWrapper(localName = "ConsultarCuentasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCuentasResponse")
    public ArrayOfCuentasBE consultarCuentas(
        @WebParam(name = "reqCuentas", targetNamespace = "http://tempuri.org/")
        CuentasBE reqCuentas);

}
