
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsPagosProgramados", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/frank/Desktop/Cliente/WsPagosProgramados.wsdl")
public class WsPagosProgramados
    extends Service
{

    private final static URL WSPAGOSPROGRAMADOS_WSDL_LOCATION;
    private final static WebServiceException WSPAGOSPROGRAMADOS_EXCEPTION;
    private final static QName WSPAGOSPROGRAMADOS_QNAME = new QName("http://tempuri.org/", "WsPagosProgramados");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/frank/Desktop/Cliente/WsPagosProgramados.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPAGOSPROGRAMADOS_WSDL_LOCATION = url;
        WSPAGOSPROGRAMADOS_EXCEPTION = e;
    }

    public WsPagosProgramados() {
        super(__getWsdlLocation(), WSPAGOSPROGRAMADOS_QNAME);
    }

    public WsPagosProgramados(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPAGOSPROGRAMADOS_QNAME, features);
    }

    public WsPagosProgramados(URL wsdlLocation) {
        super(wsdlLocation, WSPAGOSPROGRAMADOS_QNAME);
    }

    public WsPagosProgramados(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPAGOSPROGRAMADOS_QNAME, features);
    }

    public WsPagosProgramados(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPagosProgramados(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsPagosProgramadosSoap
     */
    @WebEndpoint(name = "WsPagosProgramadosSoap")
    public WsPagosProgramadosSoap getWsPagosProgramadosSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WsPagosProgramadosSoap"), WsPagosProgramadosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPagosProgramadosSoap
     */
    @WebEndpoint(name = "WsPagosProgramadosSoap")
    public WsPagosProgramadosSoap getWsPagosProgramadosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WsPagosProgramadosSoap"), WsPagosProgramadosSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPAGOSPROGRAMADOS_EXCEPTION!= null) {
            throw WSPAGOSPROGRAMADOS_EXCEPTION;
        }
        return WSPAGOSPROGRAMADOS_WSDL_LOCATION;
    }

}
