
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsPrestamosSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsPrestamosSoap {


    /**
     * 
     * @param reqPrestamos
     * @return
     *     returns org.tempuri.ArrayOfPrestamosBE
     */
    @WebMethod(operationName = "ConsultarPrestamos", action = "http://tempuri.org/ConsultarPrestamos")
    @WebResult(name = "ConsultarPrestamosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarPrestamos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarPrestamos")
    @ResponseWrapper(localName = "ConsultarPrestamosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarPrestamosResponse")
    public ArrayOfPrestamosBE consultarPrestamos(
        @WebParam(name = "reqPrestamos", targetNamespace = "http://tempuri.org/")
        PrestamosBE reqPrestamos);

}
