
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsPrestamos", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8056/WsPrestamos.asmx?wsdl")
public class WsPrestamos
    extends Service
{

    private final static URL WSPRESTAMOS_WSDL_LOCATION;
    private final static WebServiceException WSPRESTAMOS_EXCEPTION;
    private final static QName WSPRESTAMOS_QNAME = new QName("http://tempuri.org/", "WsPrestamos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8056/WsPrestamos.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPRESTAMOS_WSDL_LOCATION = url;
        WSPRESTAMOS_EXCEPTION = e;
    }

    public WsPrestamos() {
        super(__getWsdlLocation(), WSPRESTAMOS_QNAME);
    }

    public WsPrestamos(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPRESTAMOS_QNAME, features);
    }

    public WsPrestamos(URL wsdlLocation) {
        super(wsdlLocation, WSPRESTAMOS_QNAME);
    }

    public WsPrestamos(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPRESTAMOS_QNAME, features);
    }

    public WsPrestamos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPrestamos(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsPrestamosSoap
     */
    @WebEndpoint(name = "WsPrestamosSoap")
    public WsPrestamosSoap getWsPrestamosSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WsPrestamosSoap"), WsPrestamosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPrestamosSoap
     */
    @WebEndpoint(name = "WsPrestamosSoap")
    public WsPrestamosSoap getWsPrestamosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WsPrestamosSoap"), WsPrestamosSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPRESTAMOS_EXCEPTION!= null) {
            throw WSPRESTAMOS_EXCEPTION;
        }
        return WSPRESTAMOS_WSDL_LOCATION;
    }

}
